### ISSUE TITLE
orgit causes org-export to fail

### ISSUE THREAD

**Issue by dhaley** [magit/orgit#10]
I'm using the latest HEAD from the master branch.

With the following orbit link in an org mode file:

[[orgit:~/html/eeremultimedia/solar][www.eeremultimedia.energy.gov/solar]]

When I do org-export to html, I get this error:

if: Cannot determine public remote for ~/html/eeremultimedia/solar

This causes my export to HTML to fail.  Is there any work-around to this bug or some config setting that would solve this problem?

**Comment by tarsius** [comment]
It's not a bug but a feature, and it is described in the library header.

**Comment by tarsius** [comment]
Org does have a "make broken links non-fatal" option. I didn't find it taking a quick look, but it does exist. (Please post it here once you have found it.)

**Comment by kyleam** [comment]
> Org does have a "make broken links non-fatal" option.

org-export-with-broken-links

**Comment by dyereh** [comment]
Thanks guys - I tried setting org-export-with-broken-links to both t and mark as per the variable description but the export still fails

Should setting this variable `t` prevent a total export failure when I hit `(error "Cannot determine public url for %s" path)` in `orgit-export`?

**Comment by tarsius** [comment]
I was assuming it would but it appears link types have to explicitly support this. Reopening as a reminder to do that.

**Comment by dyereh** [comment]
@tarsius thanks for the speedy fix! Works will with `org-export-with-broken-link` set to `t` or `'mark`. 

Do you think there'd be any value in providing a hint in the about the availability of the `org-export-with-broken-link` variable when an export fails. I believe this variable is default `nil` so others just getting into this might have trouble discovering the variable

**Comment by tarsius** [comment]
I was actually considering making the errors more like the respective errors from exporters that are part of org itself. Doing that would make them a bit less helpful. Implementing your proposal would make them a bit more helpful and noisy. I am gonna compromise and leave things as-is.

IMO it would make sense to enable this by default, but it is the org maintainers who would have to decide to do so.

**Comment by dyereh** [comment]
@tarsius yup that's a fair point. At the very least there is documentation here that the error messages will point to
