### ISSUE TITLE
orgit is listed as an incompatible package in MELPA

### ISSUE THREAD

**Issue by jkitchin** [magit/orgit#11]
orgit is listed as an incompatible package in MELPA because of the org version requirement, so it can't be installed. It seems like most packages don't specify an org version, and the ones that do end up listed as incompatible for some reason. 

![screen shot 2016-07-08 at 7 40 12 am](https://cloud.githubusercontent.com/assets/1610070/16686324/454c3afa-44df-11e6-977b-70e27dd0804d.png)

**Comment by npostavs** [comment]
The org version in Emacs is 8.2, to get 8.3 I think you need to install from `http://orgmode.org/elpa/` as explained at http://orgmode.org/elpa.html. 

(I don't use orgit, so I have no idea if it actually requires org 8.3 or not.)

**Comment by jkitchin** [comment]
I have org-mode installed. That isn't the issue. The problem is the package requirement in orgit makes it uninstallable.

**Comment by npostavs** [comment]
Oh, you have org 8.3.3 (or greater) installed? Via package.el? Then this sounds like a package.el bug.

**Comment by jkitchin** [comment]
I have 8.3.4 installed. Maybe it is a package.el bug, but it prevents orgit
from being installed via melpa. A workaround is to just remove (org
"8.3.3") from the package requires.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by npostavs** [comment]
I just tried installing in a fresh Emacs and it works fine.

Before:
![orgit-preinstall-screenshot](https://cloud.githubusercontent.com/assets/287742/16690692/10b637b0-44f7-11e6-9b75-d813ed7384bd.png)

After:
![orgit-postinstall-screenshot](https://cloud.githubusercontent.com/assets/287742/16690691/10b58612-44f7-11e6-8316-9bae92f4613d.png)




Tried with Emacs 24.5, 25.0.95, 25.1.50

**Comment by jkitchin** [comment]
hm. I guess I have some local issue then.  Thanks for looking into it.
