### ISSUE TITLE
orgit stores a link to the branch instead of to the commit for the latest commit

### ISSUE THREAD

**Issue by joonro** [magit/orgit#12]
Hi,

Thanks for the great package. 

I found that when I store a link to a commit, if the commit is the latest one (the tip of the branch), orgit stores a link to the branch (like `(magit rev feature/branch)`) instead of the one to the commit (like `(magit rev a9ad864)`. For previous commits, orgit correctly stores the link to the commit.

Would it be possible to change the behavior so it stores the link to the commit? 

Thank you very much!

**Comment by kyleam** [comment]
> I found that when I store a link to a commit, if the commit is the
> latest one (the tip of the branch), orgit stores a link to the
> branch (like (magit rev feature/branch)) instead of the one to the
> commit (like (magit rev a9ad864).

Yes, I think that using the commit ID is better here.  If I am storing
a link in a rev buffer, I always want to point to the commit rather
than whatever the branch points to at the time I follow the link.

However, the way that you request for it to be is actually the way it
used to be.  faf8a24 (orgit-rev-store: preserve refs and abbreviate
hashes, 2016-01-19) intentionally changed it to the current behavior.
So, perhaps Jonas had a reason or use case in mind that I'm not
thinking about.  We'll have to wait for him to [get back in August][break]
to see what he thinks.

[break]: https://github.com/magit/magit/issues/2699

**Comment by joonro** [comment]
Thanks for the reply! I hope to have an option which can change this back to the previous behavior. Currently I'm manually editing the links after `org-insert-link`. :)
