### ISSUE TITLE
relative directory?

### ISSUE THREAD

**Issue by unhammer** [magit/orgit#14]
How would I store a relative directory? I'm linking to a revision from an org-file within the same repo; the repo may be stored in different places, but it seems like orgit-open wants to set default-directory no matter what the path is. 

I tried "." or empty string, but that seemed to go to "~".

**Comment by tarsius** [comment]
I've just fixed that. Thanks for reporting. With `1.2` you can now use either the empty string `.` or `./`. You can also use other relative links e.g. to neighboring repositories.

**Comment by chaoflow** [comment]
@tarsius Is this still support or am I misunderstanding it?

Having a org-file within the same repository, I would expect:
```
orgit-rev:./::SHA
```
but instead I get: orgit--repository-directory: Cannot open link; no entry for "./" in ‘magit-repository-directories’ -- same for just "."

**Comment by tarsius** [comment]
I've pushed a fix for that regression.
