### ISSUE TITLE
orgit-export fails if path is missing trailing '/'

### ISSUE THREAD

**Issue by brianhlin** [magit/orgit#15]
**orgit version:** 20160801.715 from ELPA

With `org.remote` set in my git config, `[[orgit:~/foo][foo]]` yields the following error:

`orgit-export: Cannot determine public remote for ~/foo`

Whereas `[[orgit:~/foo/][foo]]` exports as expected.

**Comment by tarsius** [comment]
I've just pushed a fix. Please verify this fixes the issue for you.

**Comment by brianhlin** [comment]
Works, thanks!
