### ISSUE TITLE
Add hook to automatically create orgit link to last commit after a commit

### ISSUE THREAD

**Issue by dakra** [magit/orgit#19]
My usual workflow is to
- clock-in a org task
- do the work
- commit

That's probably the same for most, but then I also want a NOTE to this commit in my TODO so I have to do as well:

- open the last commit in magit
- Copy the orgit link
- Goto my clocked in task and make the note with a link

So I want to automate the above 3 steps.
Maybe just an option to auto-copy the orglink to the clipboard after a commit is enough,
or maybe some way to always add a note to the current clocked-in task.

I asked the same on gitter where @tarsius said:
```
You could add a function to git-commit-setup-hook which in turn adds a function
which does the actual work to with-editor-post-finish-hook. If you cannot piece
it together based on that, then feel free to open a feature request in the orgit
repository
```
I had a hard time getting the last commit id, so here I am ;)

**Comment by tarsius** [comment]
For that you can use `(magit-git-string "rev-parse" "HEAD")`.

**Comment by dakra** [comment]
Thank you. That was missing.
I now have the following function in my config:
```elisp
(add-hook 'git-commit-setup-hook
          (lambda ()
            (add-hook 'with-editor-post-finish-hook
                      (lambda ()
                        (let* ((repo (abbreviate-file-name default-directory))
                               (rev (magit-git-string "rev-parse" "HEAD"))
                               (link (format "orgit-rev:%s::%s" repo rev))
                               (desc (format "%s (magit-rev %s)" repo rev)))
                          (push (list link desc) org-stored-links)))
                      t t)))
```

**Comment by dakra** [comment]
Hmm, my function above only works most of the time.
Sometimes I get the rev id from the commit before.
So my guess is that the `with-editor-post-finish-hook` fires before the actual git commit command is finished.

Could that be the case and if so, is there another way besides adding a small timer or something?

**Comment by tarsius** [comment]
Yes, that must be what is happening. In fact the function that does run the hook already adds a 0.1s delay before doing so, but it appears that's not always enough.
