### ISSUE TITLE
Better git link support

### ISSUE THREAD

**Issue by kvaneesh** [magit/orgit#23]
org-git-link can read git links of type git:<filename>::SHA1::linenum . But it won't create one like that. It also can't create a git link from a buffer created using magit-show . Ie, i use magit-blame, visit the file from the blame buffer and want to use org-store-link there. We would need a better integration with git to do that. Can we get orgit to create git links from buffers created via magit-blame?

**Comment by tarsius** [comment]
Anyway, I think you want to link to files in a working-tree and/or as stored in a commit and that (1) is beyond the scope of this package and (2) won't be necessary once I have released `git-handler.el`, a file handler for git blobs and trees, as that will allow visiting blobs ("files as stored in a commit") as if the where actually checked out.

**Comment by j-martin** [comment]
Hi @tarsius,

I was going to open an issue to add support for `magit-blame` to `orgit-store-link`, but it seems like this is what it being requested here. While https://github.com/magit/magit/issues/2958, make a lot of sense (make supporting blame and show), I am not 100% sure how supporting `magit-blame` is outside the scope of orgit.

I would also like that `orgit-store-link` on any buffer/git file would store the link to the file and commit at point. `[[orgit-rev:/file/path::sha][/file/path (magit-rev sha)]]`. There again, it might be outside the scope of orgit. 

My use case is to be able to take notes when scoping out work in a repo.

**Comment by j-martin** [comment]
Sounds good, thanks for the clarifications.
