### ISSUE TITLE
Option to store commit hash insteaf of ref

### ISSUE THREAD

**Issue by Ambrevar** [magit/orgit#26]
I see there is https://github.com/magit/orgit/pull/13 and yet it does not work for me.
In

```lisp
(defun orgit-rev-store-1 (rev)
  (let ((repo (abbreviate-file-name default-directory)))
    (unless (magit-ref-p rev)
      (setq rev (cond (current-prefix-arg      (magit-get-shortname rev))
                      (orgit-abbreviate-hashes (magit-rev-abbrev rev))
                      (t                       (magit-rev-parse rev)))))
    (org-store-link-props
     :type        "orgit-rev"
     :link        (format "orgit-rev:%s::%s" repo rev)
     :description (format "%s (magit-rev %s)" repo rev))))
```
the first `(magit-ref-p rev)` is non-nil if I try to store the link on master.  Thus the link will be
`/path/ (magit-rev master)`.

I'd like to get the commit hash instead of "master".

**Comment by kyleam** [comment]
Yeah, the rev-store behavior has seen quite a few tweaks trying to fit the range of personal preferences (so much for my "only hashes make sense" in 44a05c5 :]).  I think a behavior that reasonably accommodates everyone would be

  * if `rev` is a hash, store hash (full or abbreviated depended on `orgit-abbreviate-hashes`).  With prefix argument, store short name (i.e., "master" or ""v1.5.3~1"").

  * if `rev` is a ref, store ref.  With prefix argument, store hash (full or abbreviated depended on `orgit-abbreviate-hashes`).

IOW make the prefix argument toggle "hash" and "ref/name" representations, given the starting point.

**Comment by Ambrevar** [comment]
I'm not sure this is a reasonable behaviour, because then the user has to make out when to use `C-u` and when not.  It would stir confusion I think.

What would make more sense in my opinion is to have a `defcustom` boolean to choose to get always hashes or not, and use `C-u` to reverse the behaviour of the defcustom.
Makes sense?

**Comment by tarsius** [comment]
I agree with @Ambrevar. Its not always obvious whether the base value is a ref or a rev. For example in a log, is the commit at point a rev or a ref when a branch points at it? What if that is so but it is not visible because `--decorate` is disabled?

**Comment by kyleam** [comment]
@Ambrevar
> I'm not sure this is a reasonable behaviour, because then the user has to make out when to use `C-u` and when not. It would stir confusion I think.
>
> What would make more sense in my opinion is to have a `defcustom` [...]

Fair enough.  A defcustom does sound like the better option.

@tarsius
>  Its not always obvious whether the base value is a ref or a rev.

To add to that: The value stored in `magit-refresh-args` isn't consistent between revision-displaying commands.  Called from the log, `magit-diff-show-or-scroll-up` will use the commit (abbreviated) while `magit-show-commit` will use the ref or ref-based short name.
