### ISSUE TITLE
Resolve repo location dynamically

### ISSUE THREAD

**Issue by Ambrevar** [magit/orgit#27]
When collaborating with several people on an Org file, it would be nice if the orgit links would work across different setups.  In particular, the repository locations may vary, which would break the links (and relative links can be restrictive).

I can think of the following options:

- Only store the name of the root directory.  When opening the link, look up the directory in a dedicated `orgit-path` variable.  First match is taken.

Example: `(setq orgit-path '("~/common-lisp" "~/source" "~/projects"))`.  Then if link is
`orgit-rev:project-foo::master` and there is a `~/source/foo` folder, `org-rev-open` knows that this is the directory of the repository.

- Same as above with the path variable, but instead of looking up a directory name (which could vary across configurations), look up something that could identify the repo uniquely in all the folders found in `orgit-path`.  For example, we could look the remote URL.

Better: make this a customizable function so that the users can choose how to lookup repositories.

Thoughts?

**Comment by tarsius** [comment]
There's already a variable that could be used for this `magit-repository-directories`.

**Comment by Ambrevar** [comment]
Nice!  Didn't know about that variable, very useful.  I've update the PR to use it.
