### ISSUE TITLE
Functions should be autoloaded

### ISSUE THREAD

**Issue by aecay** [magit/orgit#3]
The autoloaded `eval-after-load` functions in this library modify `org-store-link-functions`, but the functions which this library adds to that hook are not themselves autoloaded.  This means that a user who has installed this package, but not added an explicit `require` to their configuration, will get "function not defined" errors when org tries to call these functions.

I think at least the `orgit-*-store` functions must be autoloaded.  Probably the `-open` and `-export` ones ought to be as well.

**Comment by tarsius** [comment]
Thanks for reporting this and sorry for forgetting about it for so long. The relevant functions are now autoloaded.

**Comment by aecay** [comment]
Thanks.
