### ISSUE TITLE
Store line number in orgit-rev

### ISSUE THREAD

**Issue by chaoflow** [magit/orgit#33]
I'd like to record notes to specific lines of a commit, not just the commit itself. Is there already a way to achieve this?

Note: I don't mean a specific line in a file changed by a commit, but the line of the diff as displayed by magit-revision.

**Comment by tarsius** [comment]
No that does not exist.

**Comment by chaoflow** [comment]
@tarsius What do you think about it and do you see a way to implement it? Is there some way I can help?

**Comment by tarsius** [comment]
I don't intend to implement this anytime soon. If you want to give it a try feel free to do so. I think those are the two mean areas you would have to deal with:

1. Determining the location within a diff and going to a location within a diff. There's code for doing that sort of thing in Magit already. Most of it is located in the "Visit Commands" section of `magit-diff.el` I believe.
2. Figure out how Org mode does line handling and do the same here.
