### ISSUE TITLE
Opening link from outside repository

### ISSUE THREAD

**Issue by tarjeiba** [magit/orgit#34]
I fear this is the wrong place to ask, but is there any way to open the links from a file outside the repository that is being linked to?

I have a global todo list, where I have different TODOS for different projects listed, can I insert a org-log link, e.g, [[orgit-log:~/repos/konfig/::("master")]], and have it open correctly when I use `C-c C-o`?

**Comment by kyleam** [comment]
That should work (and I can confirm that it doesn't).  It's a regression, probably from when things were rewritten for changes on Magit's end.  I'm not free at the moment to investigate any further, though.

**Comment by tarsius** [comment]
Or the very latest commit; but I am on the jump too.
