### ISSUE TITLE
FR: link to issues/PRs via Forge

### ISSUE THREAD

**Issue by aspiers** [magit/orgit#36]
I might have missed something but it looks like it is not currently possible to link to issues or PRs via Forge, and I thought it would be cool if it was ;-)

**Comment by kyleam** [comment]
Forge support came up in gh-24, and now there is [orgit-forge][0].  I don't personally use it, but that sounds like what you're looking for.

[0]: https://github.com/magit/orgit-forge

**Comment by aspiers** [comment]
Oh wow cool, thanks a lot!
