### ISSUE TITLE
`orgit-*-complete-link` doesn't respect `orgit-store-repository-id`

### ISSUE THREAD

**Issue by mohkale** [magit/orgit#37]
At the moment if we have `orgit-store-repository-id` set to true and try to insert an orgit link (eg: `org-insert-link-global`) you complete to a repository in your `magit-repository-directories` but orgit still inserts an absolute link even though it should be relative.

`org-store-link` respects `orgit-store-repository-id` so other completion commands in orgit should as well.

**Comment by tarsius** [comment]
Oh... you worked on it too. Looks like I looked at this a few minutes to early.

Thanks!

**Comment by mohkale** [comment]
@tarsius 

Thanks for adding this (and for coming up with a much more elegent solution) :smile:.
