### ISSUE TITLE
Make orgit save and rexecute git command

### ISSUE THREAD

**Issue by tuhdo** [magit/orgit#4]
While storing a particular commit is great. It would be even nicer if we can store a git grep command (i.e. grep for author or a string in commit mesage) and later be rexecuted, don't you think? So, we don't have to rename a grep buffer when we want to search for another author or a string, and to re-execute, it's as simple as pressing `C-c C-o`.

**Comment by tarsius** [comment]
To celebrate the first anniversary of this feature request, I have just started working on it.

**Comment by tuhdo** [comment]
Awesome! Thanks :+1:

**Comment by tarsius** [comment]
And another year later, I have finally implemented this. See #20.
