### ISSUE TITLE
Add links to files at a revision

### ISSUE THREAD

**Issue by moogah** [magit/orgit#48]
What I'm looking for is I think what the removed org-git-link library would do.  It's very common for me to want to reference a specific line in documentation, which of course becomes fragile if I don't refer to the specific commit [like this, for instance](https://github.com/magit/orgit/blob/6dc4d4bfffd6c11550952203a51346b13e120165/orgit.el#L41).

Playing around with `magit-find-file` appears to provide a lot of what is needed, but I'm new to elisp and strugging to get a start on how to add this myself.

**Comment by tarsius** [comment]
I don't plan to add support to link to files/blobs to this package. I do however plan implement such functionality in a more general and powerful way in a new packages. See https://github.com/magit/orgit/issues/23#issuecomment-450589483. I realize this plan hasn't materialized for quite a while, but it's a top-priority for next year.

**Comment by moogah** [comment]
That's fantastic news!  This kind of functionality isn't what I thought I started using emacs for, but it's turning out to be some of the most useful. I'll be watching for any updates on development, and in the meantime attempting to hack it together myself.
