### ISSUE TITLE
What about the other direction: magit linking to locations in org-mode files?

### ISSUE THREAD

**Issue by treyharris** [magit/orgit#9]
This may be out of scope, but if you have an idea or know where it should go I'll be happy to send it the correct way (or figure it out myself if I have a hint)...

When you hit `RET` for `magit-visit-item` in a diff of an org-mode file, you don't visit the line described by the diff; instead you visit the collapsed heading. There's an `org-reveal` for this purpose, I think, but I can't figure out how to hook it to make it work.

Thanks!

**Comment by kyleam** [comment]
Yes, I think the magit repo is the place for this issue.  My
preference would be to add a hook to magit-diff-visit-file, which you
could then set to something like

    (lambda ()
      (when (derived-mode-p 'org-mode)
        (org-show-context)))

**Comment by tarsius** [comment]
I have added such a hook, which you can use like

```lisp
(add-hook 'magit-diff-visit-file-hook
          (lambda ()
            (when (derived-mode-p 'org-mode)
              (org-reveal))))
```

(Note that the hook is run without ever being explicitly definde.)

Alternatively you could also use `{,global}-reveal-mode`, which has the advantage that it also works in buffers where `outline-minor-mode` is enabled.
